# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Observable_and_Bind' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Observable_and_Bind
	pod 'RxSwift'
	pod 'RxCocoa'

  target 'Observable_and_BindTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Observable_and_BindUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
