# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Driver_Signal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'RxSwift', '5.0.1'
  pod 'RxCocoa', '5.0.1'

  # Pods for Driver_Signal

end
